name: 'Reusable Go Action'
description: 'Set up Go and run a command'

inputs:
  command:
    description: Command to run
    required: true

  go-version:
    description: Go version to use
    default: '1.25'
    required: false

  cache:
    description: Whether to cache dependencies
    default: 'true'
    required: false

  upload-coverage:
    description: Whether to upload coverage reports
    default: 'false'
    required: false

  codacy-token:
    description: Codacy project token for uploading coverage
    required: false

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v7

    - name: Set up Go
      uses: actions/setup-go@v7
      with:
        go-version: ${{ inputs.go-version }}
        cache: ${{ inputs.cache }}

    - name: Run command
      shell: bash
      run: ${{ inputs.command }}

    - name: Upload test coverage reports
      if: ${{ inputs.upload-coverage == 'true' }}
      uses: codecov/codecov-action@v3

    - name: Check for Codacy token
      if: ${{ inputs.upload-coverage == 'true' }}
      id: codacy-secret-check
      shell: bash
      env:
        CODACY_PROJECT_TOKEN: ${{ inputs.codacy-token }}
      run: |
        if [ -n "$CODACY_PROJECT_TOKEN" ]; then
          echo "available=true" >> "$GITHUB_OUTPUT"
        else
          echo "available=false" >> "$GITHUB_OUTPUT"
        fi

    - name: Check inadequate permissions
      if: ${{ steps.codacy-secret-check.outputs.available != 'true' && inputs.upload-coverage == 'true' }}
      shell: bash
      env:
        ACTOR: ${{ github.actor }}
      run: |
        if [ "$ACTOR" = "dependabot[bot]" ]; then
          echo >&2 "Unable to access secrets as unprivileged dependabot."
        else
          echo >&2 "Inadequate permissions or missing secret value."
        fi
        exit 0

    - name: Run Codacy coverage reporter
      if: ${{ steps.codacy-secret-check.outputs.available == 'true' && inputs.upload-coverage == 'true' }}
      shell: bash
      env:
        CODACY_PROJECT_TOKEN: ${{ inputs.codacy-token }}
      run: bash <(curl -Ls https://coverage.codacy.com/get.sh)
