name: Re-useable Danger CI

on:
  workflow_call:
    inputs:
      node_version:
        description: Node version to use
        required: false
        type: string
        default: 16.x
    secrets:
      token:
        description: Github Token to write to PRs
        required: true

jobs:
  dangerci:
    name: Danger CI
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use NodeJS ${{ inputs.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node_version }}

      - name: Get yarn cache directory path
        id: cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: cache # use this to check for `cache-hit` (`steps.cache.outputs.cache-hit != 'true'`)
        with:
          path: |
            **/node_modules
            **/.eslintcache
            ${{ steps.cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-cache-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Danger CI Check
        uses: danger/danger-js@9.1.8
        env:
          CI: true
          GITHUB_TOKEN: ${{ secrets.token }}
          DANGER_GITHUB_API_TOKEN: ${{ secrets.token }}
