# Reference:https://github.com/marketplace/actions/build-and-push-docker-images
# Used when pushing images to Github Container Registry
name: Re-useable Github Container Registry

on:
  workflow_call:
    inputs:
      tag:
        description: Tag name of the image
        type: string
        required: false
        default: latest
    secrets:
        token:
            description: Github Token
            required: true

jobs:

  push_docker_image:
    name: Push Docker Image Github Container Registry
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      # https://github.com/docker/build-push-action/blob/v2.5.0/docs/advanced/tags-labels.md
      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/${{ github.repository }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=branch
            type=raw,value=latest,enable={{is_default_branch}}
            type=semver,pattern={{version}},value=${{ inputs.tag }}            
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        id: docker_cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log In to GitHub Container Registry
        if: github.event_name != 'pull_request'
        id: ghcr_login
        uses: docker/login-action@v1
        with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.token }}

      - name: Push Image to Docker Hub Registry
        uses: docker/build-push-action@v2
        id: docker_build
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          labels: ${{ steps.meta.outputs.labels }}
