# Reusable Go lint workflow
# 
# Usage:
# name: Lint # Name of the workflow
#
# on: [ push ]
#
# permissions:
#   contents: read
#   pull-requests: read
#
# jobs:
#   lint: # name of the job
#      name: Lint
#      uses: SanctumLabs/ci-workflows/.github/workflows/go-lint.yml@main
#      with:
#        go-version: 1.26 # Go version to use

name: Reuseable Go lint workflow

on:
  workflow_call:
    inputs:
        platform:
          description: Platform to run on
          default: 'ubuntu-latest'
          type: string
          required: false
        go-version:
          description: Go Version to use
          default: '1.26'
          type: string
          required: false
        cache:
          description: whether to cache dependencies
          default: true
          type: boolean
          required: false
        working-directory:
          description: The working directory to run linting
          default: '.'
          type: string
          required: false  

jobs:
  lint:
    runs-on: ${{ inputs.platform }}
    steps:
        - name: Checkout
          uses: actions/checkout@v7

        - name: Install Go
          uses: actions/setup-go@v7
          with:
            go-version: ${{ inputs.go-version }}
            cache: ${{ inputs.cache }}

        - name: golangci-lint
          uses: golangci/golangci-lint-action@v9.3.0
          with:
            working-directory: ${{ inputs.working-directory }}
