name: Reuseable Go Test workflow

on:
  workflow_call:
    inputs:
        platform:
          description: Platform to run on
          default: 'ubuntu-latest'
          type: string
          required: false
        go-version:
          description: Go Version to use
          default: '1.20'
          type: string
          required: false
        cache:
          description: whether to cache dependencies
          default: true
          type: boolean
          required: false
        test-command:
          description: The test command to run
          type: string
          required: true

jobs:
  test:
    runs-on: ${{ inputs.platform }}
    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Install Go
          uses: actions/setup-go@v5
          with:
            go-version: ${{ inputs.go-version }}
            cache: ${{ inputs.cache }}

        - name: Running test command ${{ inputs.test-command }}
          run: ${{ inputs.test-command}}
