# Used to run builds with bun as the package manager
name: Re-useable Bun Build Workflow

on:
  workflow_call:
    inputs:
      working-directory:
        description: Working Directory to use
        required: false
        default: /
        type: string
      command:
        description: Command to run for running builds
        required: true
        type: string
      bun-version:
        description: Bun Version to use
        default: '1.4.2'
        required: false
        type: string
      build-dir:
        description: Build directory that will be uploaded to artifacts
        default: build
        type: string
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Bun 
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ inputs.bun-version }}

      - name: Run ${{ inputs.command }}
        working-directory: ${{ inputs.working-directory }}
        run: ${{ inputs.command }}

      - uses: actions/upload-artifact@v7
        with:
          name: build
          path: ${{ inputs.build-dir }}
