name: Re-useable NPM Publish Workflow

on:
  workflow_call:
    inputs:
      directory:
        type: string
        required: false
        description: Root Directory where package will be published
      version:
        type: string
        description: Version of Package
        required: true
      scope:
        type: string
        description: Scope of package
        required: true
      registry:
        type: string
        description: Registry URL
        required: true
      nodeVersion:
        type: string
        required: false
        description: Node Version
        default: "16.x"
    secrets:
      npmAuthToken:
        required: true
        description: NPM Token

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    name: Publish NPM package
    permissions: write-all

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.nodeVersion }}
          registry-url: ${{ inputs.registry }}
          scope: ${{ inputs.scope }}

      - name: Check for provided directory
        id: directory-check
        env:
          PACKAGE_DIRECTORY: ${{ inputs.directory }}
        shell: bash
        run: |
          if [[ -n "$PACKAGE_DIRECTORY" ]]; then
            echo "changeDir=true" >> "$GITHUB_OUTPUT"
          else
            echo "changeDir=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Publish from ${{ inputs.directory }}
        env:
          NPM_TOKEN: ${{ secrets.npmAuthToken }}
          PACKAGE_DIRECTORY: ${{ inputs.directory }}
          PACKAGE_VERSION: ${{ inputs.version }}
        if: ${{ steps.directory-check.outputs.changeDir == 'true' }}
        run: bash .github/scripts/publish-npm.sh

      - name: Publish from root directory
        env:
          NPM_TOKEN: ${{ secrets.npmAuthToken }}
          PACKAGE_DIRECTORY: ""
          PACKAGE_VERSION: ${{ inputs.version }}
        if: ${{ steps.directory-check.outputs.changeDir != 'true' }}
        run: bash .github/scripts/publish-npm.sh
