# Re-useable Python Lint workflow using Ruff
name: Reusable Python Lint Workflow with Ruff

on:
  workflow_call:
    inputs:
      packager:
        description: Python Package manager to use, e.g pip, poetry, pipenv
        required: false
        default: poetry
        type: string
      python-version:
        description: Python Version to use
        default: '3.10'
        required: false
        type: string
      ruff-version:
        description: Ruff version to use
        default: '0.3.5'
        required: false
        type: string
      directory:
        description: Source directory to lint
        default: '.'
        required: false
        type: string
      ruff-args:
        description: Arguments to pass to ruff
        default: 'check'
        required: false
        type: string

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Ref: https://github.com/jenseng/dynamic-uses
      - name: Setup Python
        uses: jenseng/dynamic-uses@v1
        with:
          uses: sanctumlabs/ci-workflows/.github/actions/setup-python-${{ inputs.packager }}@main
          with: '{ "python-version": "${{ inputs.python-version }}" }'
      
      - name: Linting with Ruff
        uses: chartboost/ruff-action@v1
        with:
            version: ${{ inputs.ruff-version }}
            src: ${{ inputs.directory }}
            args: ${{ inputs.ruff-args }}
