# Used to run builds with package manager
name: Re-useable Python Build Workflow

on:
  workflow_call:
    inputs:
      packager:
        description: Python Package manager to use, e.g pip, poetry, pipenv
        required: false
        default: poetry
        type: string
      command:
        description: Command to run for running builds
        required: true
        type: string
      python-version:
        description: Python Version to use
        default: "3.10"
        required: false
        type: string
      install-command:
        description: Command to use to install dependencies
        default: "uv pip install -r pyproject.toml --all-extras"
        required: false
        type: string
      virtual-env-dir:
        description: Virtual environment directory
        default: ".venv"
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Ref: https://github.com/jenseng/dynamic-uses
      - name: Setup
        uses: jenseng/dynamic-uses@v1
        with:
          uses: sanctumlabs/ci-workflows/.github/actions/setup-python-${{ inputs.packager }}@main
          with: '{ "python-version": "${{ inputs.python-version }}", "install-command": "${{ inputs.install-command }}", "virtual-env-directory": "${{ inputs.virtual-env-dir }}" }'

      - name: Run ${{ inputs.command }}
        run: ${{ inputs.command }}
