# Re-useable Python Lint workflow using Poetry as the package manager
name: Reusable Python Lint Workflow

on:
  workflow_call:
    inputs:
      packager:
        description: Python Package manager to use, e.g pip, poetry, pipenv
        required: false
        default: poetry
        type: string
      command:
        description: Command to run for linting
        required: true
        type: string
      python-version:
        description: Python Version to use
        default: '3.10'
        required: false
        type: string

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Ref: https://github.com/jenseng/dynamic-uses
      - name: Setup 
        uses: jenseng/dynamic-uses@v1
        with:
          uses: sanctumlabs/ci-workflows/.github/actions/setup-python-${{ inputs.packager }}@main
          with: '{ "python-version": "${{ inputs.python-version }}" }'

      - name: Run ${{ inputs.command }}
        run: ${{ inputs.command }}
