# Used when handling releases
# Uses https://github.com/softprops/action-gh-release
name: Re-useable Release Workflow

on:
  workflow_call:
    inputs:
      name:
        description: Release Name
        required: false
        type: string
      tag_name:
        description: Github Tag Name
        required: true
        type: string

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: ${{ inputs.name }}
          tag_name: ${{ inputs.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
