# Workflow to post notifications to Slack of status of builds.
# This workflow template sends notifications to Slack when pipeline succeeds

# Required Variables:
# slack_webhook: Slack Webhook URL

# Optional Variables:
# slack_channel: Slack channel to post to
# slack_color: Slack color to post
# slack_icon: Slack icon to use when posting message
# slack_icon_emoji: Emoji Icon to post Slack messages with
# slack_username: Slack username to use when posting to Slack, this does not have to be a 'real' username
# slack_title: Slack Title to post the message with
# slack_message: message of the Slack notification
# slack_footer: Footer of the message
# Ref https://github.com/rtCamp/action-slack-notify
name: Re-useable Slack Notification

on:
  workflow_call:
    inputs:
      slack_username:
        description: Slack Username
        type: string
        required: false
        default: "Ratholos"
      slack_channel:
        description: Slack Channel to post messages to
        required: false
        default: "pipelines"
        type: string
      slack_icon:
        description: Slack Icon
        required: false
        default: https://github.com/ratholos.png?size=48
        type: string
      slack_color:
        description: Slack Color
        required: false
        default: "good"
        type: string
      slack_icon_emoji:
        description: Slack Icon Emoji
        required: false
        default: ":large_green_circle:"
        type: string
      slack_message:
        description: Slack Message
        required: false
        default: "Success"
        type: string
      slack_title:
        description: Slack Message Title
        required: false
        default: ${{ github.repository }} - ${{ github.event.workflow_run.name }} Workflow Run
        type: string
      
    secrets:
      slack_webhook:
        description: 'Slack Webhook'
        required: true

jobs:
  onNotification:
    name: Slack Notification
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: ${{ inputs.slack_channel }}
          SLACK_COLOR: ${{ inputs.slack_color }}
          SLACK_ICON: ${{ inputs.slack_icon }}
          SLACK_ICON_EMOJI: ${{ inputs.slack_icon_emoji }}
          SLACK_USERNAME: ${{ inputs.slack_username }}
          SLACK_TITLE: ${{ inputs.slack_title }}
          SLACK_MESSAGE: ${{ inputs.slack_message }}
          SLACK_FOOTER: "Regards, ${{ inputs.slack_username }}"
          SLACK_WEBHOOK: ${{ secrets.slack_webhook }}
